### ISSUE TITLE
package.json does not exist error

### ISSUE THREAD

**Issue by rendall** [rendall/simple-comment#19]
<https://simple-comment.netlify.app> errors with the following:

```
{
  "errorType": "Error",
  "errorMessage": "package.json does not exist at /package.json",
  "trace": [
    "Error: package.json does not exist at /package.json",
    " at Object.t.find (/var/task/src/verify.js:3:443031)",
    " at Object. (/var/task/src/verify.js:135:333456)",
    " at Object. (/var/task/src/verify.js:135:336547)",
    " at r (/var/task/src/verify.js:1:158)",
    " at Object. (/var/task/src/verify.js:135:333068)",
    " at r (/var/task/src/verify.js:1:158)",
    " at Object. (/var/task/src/verify.js:135:78445)",
    " at r (/var/task/src/verify.js:1:158)",
    " at Object. (/var/task/src/verify.js:245:253032)",
    " at r (/var/task/src/verify.js:1:158)"
  ]
}
```

**Comment by rendall** [comment]
webpack via `netlify-lambda` is unable to handle `bcrypt`'s dependency `pre-node-gyp` properly. Easiest solution is to just swap out `bcrypt` for `bcryptjs`
